version: '3'

services:
  nnstreamer:
    build: .
    container_name: demo
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=$DISPLAY
    entrypoint: "/workspace/nnstreamer-example/bash_script/example_object_detection_tensorflow/gst-launch-object-detection-tf.sh"
    devices:
      - "/dev/video0"
